name: 'build' 
on: # rebuild any PRs and main branch changes
  workflow_dispatch:
  pull_request:
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v2

      - name: Build and run dev container task
        uses: devcontainers/ci@v0.2
        with:
          runCmd: |
            nimble release
            cp extension.json build/
            cd build
            tar -czvf ../azbelt.tar.gz .

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            build/*.dll
            build/*.exe
            azbelt.tar.gz